// index is generated by command
// but before executing npm init make sure
// Node.js is install and its install path should added to the system's env variables

// even though in classes we export and expose both of the two classes
// but we want to use them we also need to use import
// to import them to current context env
import { Person, SoftwareEngineer } from "./classes.js";

const sebby = new Person("Sebby", "Sebby", "Male", 21);
const alex = new SoftwareEngineer("Alex", "aleustur", "Male", 33);
const software_developer_sebby = new SoftwareEngineer(
  sebby.firstName,
  sebby.lastName,
  sebby.gender,
  sebby.age,
  ["Java", "JavaScript"]
);

alex.fName = "Alexander";

// behaviors of sebby as a person
sebby.sleep();
sebby.eat();
sebby.play();

// behaviors of sebby as a developer
software_developer_sebby.sleep();
software_developer_sebby.eat();
software_developer_sebby.code();
