name: Deploy Frontend Projects

on: 
  push: 
    branches:
      - main

permissions:
  contents: write 

jobs:
  deploy-tailwind-sandbox:
    name: Deploy Tailwind CSS Sandbox 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-sandbox
        

  deploy-tailwind-projects:   
    name: Deploy Tailwind CSS Projects 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3 
      - name: To Be Implemented 
        run: |
          echo "Not Ready Yet, To Be Implemented!"