# Workflow for deploying frontend projects to GitHub Pages upon release creation

name: Deploy Frontend Projects

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies (if applicable, otherwise remove)
      - name: Install dependencies
        run: |
          if [ -f ./tailwind-css-sandbox/package.json ]; then
            cd ./tailwind-css-sandbox && npm ci
          fi

      # Optionally, build the projects if necessary (for React or similar frameworks)
      - name: Build Tailwind CSS Sandbox
        run: |
          if [ -f ./tailwind-css-sandbox/package.json ]; then
            cd ./tailwind-css-sandbox && npm run build
          fi

  deploy-tailwind-sandbox:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Tailwind CSS Sandbox to GitHub Pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-sandbox

  deploy-tailwind-mini-projects:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Deploy email-subscribe 
      - name: Deply Each Mini-Project One by One
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/mini-projects/email-subscribe
          publish_branch: gh-pages
          destination_dir: email-subscribe
      
      # Deploy image-gallery
      - name: Deploy Image Gallery 
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/mini-projects/image-gallery
          publish_branch: gh-pages
          destination_dir: image-gallery

      # Deploy pricing-cards
      - name: Deploy Pricing Cards
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/mini-projects/pricing-cards
          publish_branch: gh-pages
          destination_dir: pricing-cards
      
      # Deploy product-modal
      - name: Deploy Product Modal
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/mini-projects/product-modal
          publish_branch: gh-pages
          destination_dir: product-modal

      # Deploy login-modal
      - name: Deploy Login Modal 
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/mini-projects/login-modal
          publish_branch: gh-pages
          destination_dir: login-modal

  deploy-tailwind-website-projects:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      # Check Node.js is installed correctly 
      - name: Check Node.js Version 
        run: node --version 

      # Install dependencies 
      - name: Install Node.js Dependencies 
        run: |
          cd  ./tailwind-css-projects/website-projects/clipboard
          npm ci 
      # Build the CSS using Tailwind 
      - name: Build Tailwind CSS 
        run: | 
          cd ./tailwind-css-projects/website-projects/clipboard
          npm run build 

      # Deploy Clipboard Website Project 
      - name: Deply Website Project Cliboard 
        uses: peaceiris/action-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tailwind-css-projects/website-projects/clipboard
          publish_branch: gh-pages
          destination_dir: clipboard